{
 "title": "CPU performance",
 "tags": [
  "screeps",
  "perfomance"
 ],
 "time": { "from": "now-5h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "mode",
    "query": {}
   },
   {
    "name": "phase",
    "query": {}
   },
   { "name": "scaling", "query": "0.001" }
  ]
 },
 "panels": [
  {
   "title": "Mean CPU by Phase",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(groupByNode(scale(removeEmptySeries(stats.gauges.$shard.cpuUsage.*.*.$mode), $scaling), 4, 'sum'), 0)"
    }
   ]
  },
  {
   "title": "Mean CPU by Category",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 188 }
   ]
  },
  {
   "title": "CPU general",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.used), 'Used')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.bucket), 'Bucket')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.limit), 'Limit')"
    },
    {
     "target": "alias(scale(sumSeries(stats.gauges.$shard.cpuUsage.*.*.cpu), $scaling), 'Accounted')"
    }
   ]
  },
  {
   "title": "CPU by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#A, 'deposit')), 'deposit mining')",
     "targetFull": "alias(sumSeries(grep(groupByNode(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'structures_room_')), 'hive update structures')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'network')), 'network')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'network')), 'network')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'warcrimes')), 'warcrimes')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'log|visuals')), 'convinience')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'log|visuals')), 'convinience')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'beesMove')), 'beesMove')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'beesMove')), 'beesMove')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'rollup')), 'rollup')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'rollup')), 'rollup')"
    },
    {
     "target": "alias(absolute(sumSeries(scale(#B, -1), #C, #D, #E, #F, #G, #H, #I, #J, #K, #M, #N)), 'other')",
     "targetFull": "alias(absolute(sumSeries(scale(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), -1), alias(sumSeries(grep(groupByNode(grep(#B, '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining'), alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense'), alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures'), alias(sumSeries(grep(#B, 'network')), 'network'), alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes'), alias(sumSeries(grep(#B, 'log|visuals')), 'convinience'), alias(sumSeries(grep(#B, 'beesMove')), 'beesMove'), alias(sumSeries(grep(#B, 'rollup')), 'rollup'))), 'other')"
    }
   ]
  },
  {
   "title": "CPU by Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasSub(aliasByNode(sortByTotal(scale(removeEmptySeries(stats.gauges.$shard.cpuUsage.$phase.*.$mode), $scaling)), 4, 5), 'res([a-z0-9]{2})[a-z0-9]{22}', 'resID\\1'), '^(u)pdate\\.|^(r)un\\.', '\\1\\2.'), '\\.master_', '.m.'), '([a-z0-9]{2})[a-z0-9]{22}', 'ID\\1')"
    }
   ]
  },
  {
   "title": "Avg CPU by Process",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasSub(aliasByNode(sortByTotal(transformNull(scale(removeEmptySeries(stats.gauges.$shard.cpuUsage.$phase.*.$mode), $scaling), 0)), 4, 5), 'res([a-z0-9]{2})[a-z0-9]{22}', 'resID\\1'), '^(u)pdate\\.|^(r)un\\.', '\\1\\2.'), '\\.master_', '.m.'), '([a-z0-9]{2})[a-z0-9]{22}', 'ID\\1')"
    }
   ]
  },
  {
   "title": "CPU in Hives",
   "type": "piechart",
   "description": "Mean per tick across all hives",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sortByTotal(aliasSub(groupByNodes(transformNull(group(#B, #C, #E), 0), 'sumSeries', 0, 1), '\\.', ' '))",
     "targetFull": "sortByTotal(aliasSub(groupByNodes(transformNull(group(aliasSub(grep(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), 'master_builder_'), 'master_(builder)_([NSEW0-9]+)', '\\1'), aliasSub(aliasSub(grep(#A, '^(update|run)\\.cell_'), 'cell_([NSEW0-9]+)_([a-zA-Z0-9]+)_?([NSEW0-9]*)', '\\2'), 'res([a-z0-9]{24})', 'res'), aliasSub(aliasSub(grep(#A, '^(update|run)\\.master_cell_'), 'master_cell_([NSEW0-9]+)_([a-zA-Z0-9]+)_?([NSEW0-9]*)_?([NSEW0-9]*)', '\\2'), 'res([a-z0-9]{24})', 'resMaster')), 0), 'sumSeries', 0, 1), '\\.', ' '))"
    }
   ]
  },
  {
   "title": "Mean CPU by Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#A, '^cell_')), 'cells_structures')",
     "targetFull": "alias(sumSeries(grep(aliasSub(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), '^(update|run)\\.', ''), '^cell_')), 'cells_structures')"
    },
    {
     "target": "alias(sumSeries(grep(#A, '^master_cell_')), 'cells_masters')",
     "targetFull": "alias(sumSeries(grep(aliasSub(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), '^(update|run)\\.', ''), '^master_cell_')), 'cells_masters')"
    },
    {
     "target": "alias(sumSeries(grep(#A, 'rollup')), 'rollup')",
     "targetFull": "alias(sumSeries(grep(aliasSub(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), '^(update|run)\\.', ''), 'rollup')), 'rollup')"
    },
    {
     "target": "alias(sumSeries(grep(#A, '^master_(?!cell_)')), 'other_masters')",
     "targetFull": "alias(sumSeries(grep(aliasSub(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), '^(update|run)\\.', ''), '^master_(?!cell_)')), 'other_masters')"
    },
    {
     "target": "alias(diffSeries(sumSeries(#A), #B, #C, #E, #F), 'other_proc')",
     "targetFull": "alias(diffSeries(sumSeries(aliasSub(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), '^(update|run)\\.', '')), alias(sumSeries(grep(aliasSub(removeEmptySeries(aliasByNode(scale(stats.gauges.$shard.cpuUsage.$phase.*.$mode, $scaling), 4, 5)), '^(update|run)\\.', ''), '^master_(?!cell_)')), 'other_masters'), alias(sumSeries(grep(#A, '^cell_')), 'cells_structures'), alias(sumSeries(grep(#A, '^master_cell_')), 'cells_masters'), alias(sumSeries(grep(#A, 'rollup')), 'rollup')), 'other_proc')"
    }
   ]
  },
  {
   "title": "TOP10 Heaviest ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(scale(highest(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 10, 'avg'), $scaling), 4, 5))"
    }
   ]
  },
  {
   "title": "CPU used by Cells",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(aliasSub(aliasByNode(sortByTotal(scale(removeEmptySeries(stats.gauges.$shard.cpuUsage.$phase.*.$mode), $scaling)), 4, 5), 'res([a-z0-9]{2})[a-z0-9]{22}', 'res'), '^(u)pdate\\.|^(r)un\\.', '\\1\\2.'), '\\.master_', '.m.')"
    }
   ]
  }
 ]
}