{
 "title": "Energy economy",
 "tags": [
  "screeps",
  "economy"
 ],
 "time": { "from": "now-5h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "hiveName",
    "query": {}
   },
   { "name": "resource", "query": "energy" }
  ]
 },
 "panels": [
  { "title": "Colony info $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "shard" },
  {
   "title": "$resource per tick ",
   "type": "timeseries",
   "description": "with import/export",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(movingSum(transformNull(sumSeries(group(#E, #F)), 0), '5min'), #B), '5m average')",
     "targetFull": "alias(divideSeries(movingSum(transformNull(sumSeries(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*)), 0), '5min'), movingSum(derivative(stats.gauges.$shard.tick.current), '5min')), '5m average')"
    },
    {
     "target": "alias(divideSeries(movingSum(transformNull(sumSeries(group(#E, #F)), 0), '1hour'), #D), '1h average')",
     "targetFull": "alias(divideSeries(movingSum(transformNull(sumSeries(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*)), 0), '1hour'), movingSum(derivative(stats.gauges.$shard.tick.current), '1hour')), '1h average')"
    }
   ]
  },
  {
   "title": "Income/Expenditure",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(absolute(sumSeries(averageBelow(group(#A, #D), -0.000001))), 'Expenditure')",
     "targetFull": "alias(absolute(sumSeries(averageBelow(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local')), -0.000001))), 'Expenditure')"
    },
    {
     "target": "alias(sumSeries(averageAbove(group(#A, #D), 0.000001)), 'Income')",
     "targetFull": "alias(sumSeries(averageAbove(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local')), 0.000001)), 'Income')"
    }
   ]
  },
  {
   "title": "$resource over period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(averageAbove(groupByNode(group(#C, #D), 7, 'sum'), 0.000001)), 'Income')",
     "targetFull": "alias(sumSeries(averageAbove(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local')), 7, 'sum'), 0.000001)), 'Income')"
    },
    {
     "target": "alias(sumSeries(averageBelow(groupByNode(group(#C, #D), 7, 'sum'), -0.000001)), 'Expenditure')",
     "targetFull": "alias(sumSeries(averageBelow(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local')), 7, 'sum'), -0.000001)), 'Expenditure')"
    }
   ]
  },
  {
   "title": "$resource income ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(averageAbove(group(#A, #C), 0.000001), 7, 'sum')",
     "targetFull": "groupByNode(averageAbove(group(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*), 0.000001), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$resource expenditure ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(absolute(averageBelow(group(#A, #C), -0.000001))), 7, 'sum')",
     "targetFull": "groupByNode(removeEmptySeries(absolute(averageBelow(group(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*), -0.000001))), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$resource per tick 10m average",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(groupByNode(transformNull(removeEmptySeries(divideSeries(movingSum(group(#B, #D), '10min'), #A)), 0), 7, 'sum')), 0)",
     "targetFull": "aliasByNode(sortByTotal(groupByNode(transformNull(removeEmptySeries(divideSeries(movingSum(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local')), '10min'), movingSum(derivative(stats.gauges.$shard.tick.current), '10min'))), 0), 7, 'sum')), 0)"
    }
   ]
  },
  {
   "title": "$resource expenditure by category ",
   "type": "piechart",
   "description": "maybe some overlap but seems good",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#C, 'Queen_bee|Carpenter_bee|upkeep(?!\\.)')), 'managers')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Queen_bee|Carpenter_bee|upkeep(?!\\.)')), 'managers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Honey_bee|upgrade')), 'upgrade')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Honey_bee|upgrade')), 'upgrade')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Mason_bee|build')), 'build')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Mason_bee|build')), 'build')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'deposit')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'deposit')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Japanese_beetle')), 'mineral')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Japanese_beetle')), 'mineral')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Scarabaeus_sacer')), 'energy')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Scarabaeus_sacer')), 'energy')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Bumblebee|upkeep\\.[a-z0-9]{4}')), 'haulers')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Bumblebee|upkeep\\.[a-z0-9]{4}')), 'haulers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), 'annexes')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Orchid_Mantis|Firefly')), 'annexes')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Walking_stick|defense')), 'defense')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Walking_stick|defense')), 'defense')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth|power')), 'power')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Hercules_beetle|Atlas_moth|power')), 'power')"
    },
    {
     "target": "alias(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attackers')",
     "targetFull": "alias(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attackers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'factory|boosts')), 'production')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'factory|boosts')), 'production')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'export|terminal')), 'export')",
     "targetFull": "alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 'export|terminal')), 'export')"
    },
    {
     "target": "alias(round(diffSeries(sumSeries(#C), #A, #B, #D, #E, #F, #G, #H, #I, #J, #K, #L, #P, #Q), 10), 'other')",
     "targetFull": "alias(round(diffSeries(sumSeries(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001)))), alias(sumSeries(grep(absolute(removeEmptySeries(averageBelow(group(#O, #N), -0.000001))), 'Queen_bee|Carpenter_bee|upkeep(?!\\.)')), 'managers'), alias(sumSeries(grep(#C, 'Honey_bee|upgrade')), 'upgrade'), alias(sumSeries(grep(#C, 'Mason_bee|build')), 'build'), alias(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'deposit'), alias(sumSeries(grep(#C, 'Japanese_beetle')), 'mineral'), alias(sumSeries(grep(#C, 'Scarabaeus_sacer')), 'energy'), alias(sumSeries(grep(#C, 'Bumblebee|upkeep\\.[a-z0-9]{4}')), 'haulers'), alias(sumSeries(grep(#C, 'Walking_stick|defense')), 'defense'), alias(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), 'annexes'), alias(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth|power')), 'power'), alias(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attackers'), alias(sumSeries(grep(#C, 'factory|boosts')), 'production'), alias(sumSeries(grep(#C, 'export|terminal')), 'export')), 10), 'other')"
    }
   ]
  },
  {
   "title": "$resource on spawning",
   "type": "piechart",
   "description": "not ideal as some overlap is still there",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#C, 'Queen_bee|Carpenter_bee')), 'managers')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Queen_bee|Carpenter_bee')), 'managers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Honey_bee')), 'upgrader')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Honey_bee')), 'upgrader')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Mason_bee')), 'builder')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Mason_bee')), 'builder')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'deposits')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'deposits')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Japanese_beetle')), 'minerals')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Japanese_beetle')), 'minerals')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Scarabaeus_sacer')), 'energy')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Scarabaeus_sacer')), 'energy')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Bumblebee')), 'haulers')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Bumblebee')), 'haulers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Walking_stick')), 'defense')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Walking_stick')), 'defense')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), 'annexes')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Orchid_Mantis|Firefly')), 'annexes')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth')), 'power')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Hercules_beetle|Atlas_moth')), 'power')"
    },
    {
     "target": "alias(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attack')",
     "targetFull": "alias(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attack')"
    },
    {
     "target": "alias(diffSeries(sumSeries(#C), #A, #B, #D, #E, #F, #G, #H, #I, #J, #K, #L), 'other')",
     "targetFull": "alias(diffSeries(sumSeries(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.'))), alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Queen_bee|Carpenter_bee')), 'managers'), alias(sumSeries(grep(#C, 'Honey_bee')), 'upgrader'), alias(sumSeries(grep(#C, 'Mason_bee')), 'builder'), alias(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'deposits'), alias(sumSeries(grep(#C, 'Japanese_beetle')), 'minerals'), alias(sumSeries(grep(#C, 'Scarabaeus_sacer')), 'energy'), alias(sumSeries(grep(#C, 'Bumblebee')), 'haulers'), alias(sumSeries(grep(#C, 'Walking_stick')), 'defense'), alias(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), 'annexes'), alias(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth')), 'power'), alias(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attack')), 'other')"
    }
   ]
  },
  {
   "title": "$resource expenditure by category avg 30min",
   "type": "timeseries",
   "description": "maybe some overlap but seems good",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Queen_bee|Carpenter_bee|upkeep(?!\\.)')), '30min'), #R), 'managers')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Queen_bee|Carpenter_bee|upkeep(?!\\.)')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'managers')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Honey_bee|upgrade')), '30min'), #R), 'upgrade')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Honey_bee|upgrade')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'upgrade')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Mason_bee|build')), '30min'), #R), 'build')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Mason_bee|build')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'build')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), '30min'), #R), 'deposit')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Garden_bumblebee|Ground_beetle|Dragonfly')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'deposit')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Japanese_beetle')), '30min'), #R), 'mineral')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Japanese_beetle')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'mineral')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Scarabaeus_sacer')), '30min'), #R), 'energy')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Scarabaeus_sacer')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'energy')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Bumblebee|upkeep\\.[a-z0-9]{4}')), '30min'), #R), 'haulers')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Bumblebee|upkeep\\.[a-z0-9]{4}')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'haulers')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), '30min'), #R), 'annexes')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Orchid_Mantis|Firefly')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'annexes')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Walking_stick|defense')), '30min'), #R), 'defense')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Walking_stick|defense')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'defense')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth|power')), '30min'), #R), 'power')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Hercules_beetle|Atlas_moth|power')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'power')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect')), '30min'), #R), 'attackers')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'attackers')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'factory|boosts')), '30min'), #R), 'production')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'factory|boosts')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'production')"
    },
    {
     "target": "alias(divideSeries(movingAverage(sumSeries(grep(#C, 'export|terminal')), '30min'), #R), 'export')",
     "targetFull": "alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0), 'export|terminal')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'export')"
    },
    {
     "target": "alias(round(diffSeries(sumSeries(#C), #A, #B, #D, #E, #F, #G, #H, #I, #J, #K, #L, #P, #Q), 30min), '#R')",
     "targetFull": "alias(round(diffSeries(sumSeries(transformNull(absolute(removeEmptySeries(averageBelow(group(aliasByNode(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, 7, 8), aliasByNode(exclude(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, '_local'), 7)), -0.000001))), 0)), alias(divideSeries(movingAverage(sumSeries(grep(transformNull(absolute(removeEmptySeries(averageBelow(group(#O, #N), -0.000001))), 0), 'Queen_bee|Carpenter_bee|upkeep(?!\\.)')), '30min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')), 'managers'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Honey_bee|upgrade')), '30min'), #R), 'upgrade'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Mason_bee|build')), '30min'), #R), 'build'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), '30min'), #R), 'deposit'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Japanese_beetle')), '30min'), #R), 'mineral'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Scarabaeus_sacer')), '30min'), #R), 'energy'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Bumblebee|upkeep\\.[a-z0-9]{4}')), '30min'), #R), 'haulers'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Walking_stick|defense')), '30min'), #R), 'defense'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), '30min'), #R), 'annexes'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth|power')), '30min'), #R), 'power'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect')), '30min'), #R), 'attackers'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'factory|boosts')), '30min'), #R), 'production'), alias(divideSeries(movingAverage(sumSeries(grep(#C, 'export|terminal')), '30min'), #R), 'export')), 30min), 'movingAverage(derivative(stats.gauges.$shard.tick.current), '30min')')"
    }
   ]
  },
  { "title": "$hiveName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "hiveName" },
  {
   "title": "$resource per Tick 10m avg $hiveName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "sortBy(groupByNode(transformNull(removeEmptySeries(divideSeries(movingSum(group(#A, #D), '10min'), #B)), 0), 7, 'sum'), 'average', false)",
     "targetFull": "sortBy(groupByNode(transformNull(removeEmptySeries(divideSeries(movingSum(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*), '10min'), movingSum(derivative(stats.gauges.$shard.tick.current), '10min'))), 0), 7, 'sum'), 'average', false)"
    }
   ]
  },
  {
   "title": "$resource per tick $hiveName",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(absolute(averageAbove(group(#A, #C), 0.000001))), 7, 'sum')",
     "targetFull": "groupByNode(removeEmptySeries(absolute(averageAbove(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*), 0.000001))), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$resource expenditure $hiveName",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(absolute(averageBelow(group(#A, #C), -0.000001))), 7, 'sum')",
     "targetFull": "groupByNode(removeEmptySeries(absolute(averageBelow(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*), -0.000001))), 7, 'sum')"
    }
   ]
  }
 ]
}