{
 "title": "Resource economy",
 "tags": [
  "screeps",
  "economy"
 ],
 "time": { "from": "now-5h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "hiveName",
    "query": {}
   },
   {
    "name": "resource",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Colony info $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "shard" },
  {
   "title": "$resource per tick",
   "type": "timeseries",
   "description": "No import/export. Not even local import/export",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(transformNull(divideSeries(movingSum(sumSeries(group(#E, #F)), '1hour'), #D), 0), '1h average')",
     "targetFull": "alias(transformNull(divideSeries(movingSum(sumSeries(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*)), '1hour'), movingSum(derivative(stats.gauges.$shard.tick.current), '1hour')), 0), '1h average')"
    },
    {
     "target": "alias(transformNull(divideSeries(movingSum(sumSeries(group(#E, #F)), '5min'), #B), 0), '5m average')",
     "targetFull": "alias(transformNull(divideSeries(movingSum(sumSeries(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*)), '5min'), movingSum(derivative(stats.gauges.$shard.tick.current), '5min')), 0), '5m average')"
    }
   ]
  },
  {
   "title": "Income/Expenditure",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(absolute(sumSeries(averageBelow(group(#A, #D), -0.000001))), 'Expenditure')",
     "targetFull": "alias(absolute(sumSeries(averageBelow(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), -0.000001))), 'Expenditure')"
    },
    {
     "target": "alias(sumSeries(averageAbove(group(#A, #D), 0.000001)), 'Income')",
     "targetFull": "alias(sumSeries(averageAbove(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 0.000001)), 'Income')"
    }
   ]
  },
  {
   "title": "$resource over period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(averageAbove(groupByNode(group(#C, #D), 7, 'sum'), 0.000001)), 'Income')",
     "targetFull": "alias(sumSeries(averageAbove(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 7, 'sum'), 0.000001)), 'Income')"
    },
    {
     "target": "alias(sumSeries(averageBelow(groupByNode(group(#C, #D), 7, 'sum'), -0.000001)), 'Expenditure')",
     "targetFull": "alias(sumSeries(averageBelow(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 7, 'sum'), -0.000001)), 'Expenditure')"
    }
   ]
  },
  {
   "title": "$resource income ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNodes(removeEmptySeries(absolute(averageAbove(group(#A, #C), 0.000001))), 'sum', 6, 7)",
     "targetFull": "groupByNodes(removeEmptySeries(absolute(averageAbove(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*), 0.000001))), 'sum', 6, 7)"
    }
   ]
  },
  {
   "title": "$resource expenditure",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNodes(removeEmptySeries(absolute(averageBelow(group(#A, #C), -0.000001))), 'sum', 6, 7)",
     "targetFull": "groupByNodes(removeEmptySeries(absolute(averageBelow(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*), -0.000001))), 'sum', 6, 7)"
    }
   ]
  },
  {
   "title": "$resource per tick 10m average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(transformNull(sortByTotal(removeEmptySeries(divideSeries(movingAverage(groupByNode(group(#B, #D), 7, 'sum'), '10min'), #A))), 0), 0)",
     "targetFull": "aliasByNode(transformNull(sortByTotal(removeEmptySeries(divideSeries(movingAverage(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 7, 'sum'), '10min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '10min')))), 0), 0)"
    }
   ]
  },
  { "title": "$hiveName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "hiveName" },
  {
   "title": "$resource per Tick $hiveName",
   "type": "timeseries",
   "description": "No import/export. Not even local import/export",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(transformNull(divideSeries(movingSum(sumSeries(group(#A, #D)), '10min'), #B), 0), '10m average')",
     "targetFull": "alias(transformNull(divideSeries(movingSum(sumSeries(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*)), '10min'), movingSum(derivative(stats.gauges.$shard.tick.current), '10min')), 0), '10m average')"
    }
   ]
  },
  {
   "title": "$resource income $hiveName",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNodes(removeEmptySeries(absolute(averageAbove(group(#A, #C), 0.000001))), 'sum', 6, 7)",
     "targetFull": "groupByNodes(removeEmptySeries(absolute(averageAbove(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*), 0.000001))), 'sum', 6, 7)"
    }
   ]
  },
  {
   "title": "$resource expenditure $hiveName",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNodes(removeEmptySeries(absolute(averageBelow(group(#A, #C), -0.000001))), 'sum', 6, 7)",
     "targetFull": "groupByNodes(removeEmptySeries(absolute(averageBelow(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*), -0.000001))), 'sum', 6, 7)"
    }
   ]
  }
 ]
}