{
 "title": "Room overview",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "hiveName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$hiveName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "hiveName",
   "targets": [
    {}
   ]
  },
  {
   "title": "RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$shard.hives.$hiveName.controller.level, 2)"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(divideSeries(stats.gauges.$shard.hives.$hiveName.controller.progress, #B), 2)",
     "targetFull": "aliasByNode(divideSeries(stats.gauges.$shard.hives.$hiveName.controller.progress, stats.gauges.$shard.hives.$hiveName.controller.progressTotal), 2)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.$shard.hives.$hiveName.controller.progressTotal, #B), #C)",
     "targetFull": "divideSeries(diffSeries(stats.gauges.$shard.hives.$hiveName.controller.progressTotal, stats.gauges.$shard.hives.$hiveName.controller.progress), scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.$shard.hives.$hiveName.controller.progress), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.hives.$hiveName.controller.progress), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.hives.$hiveName.controller.progress), derivative(stats.gauges.$shard.tick.current)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hiveName.controller.progress), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hiveName.controller.progress), derivative(stats.gauges.$shard.tick.current)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$shard.hives.$hiveName.energy.spawners, 'Spawns and Extensions')"
    },
    {
     "target": "alias(stats.gauges.$shard.hives.$hiveName.energy.storage, 'Storage')"
    },
    {
     "target": "alias(stats.gauges.hives.$hiveName.energy.terminal, 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(stats.gauges.$shard.hives.$hiveName.energy.storage, 'Storage'), alias(stats.gauges.$shard.hives.$hiveName.energy.spawners, 'Spawns and Extensions'), alias(stats.gauges.hives.$hiveName.energy.terminal, 'Terminal')), 'Total')"
    }
   ]
  }
 ]
}