global.SPAWN_NAME = "Spawn1"
global.ROOM_NAME =  "E21S57"

global.HARVESTERS_DESIRED = 5
global.BUILDERS_DESIRED = 1
global.UPGRADERS_DESIRED = 4

global.HARVESTERS_ROLENAME = "harvester"
global.BUILDERS_ROLENAME = "builder"
global.UPGRADERS_ROLENAME = "upgrader"

global.WEAK_PARTS = [WORK,CARRY,MOVE] //200

global.BUMBLEBEE_TYPENAME = "bumblebee"
global.BUMBLEBEE_PARTS = [WORK,WORK,CARRY,CARRY,CARRY,CARRY, MOVE,MOVE,MOVE]
global.BUMBLEBEE_COST = 550


global.FIREANT_TYPENAME = "fireAnt"
global.FIREANT_PARTS = [TOUGH,TOUGH,ATTACK,ATTACK,ATTACK, MOVE,MOVE,MOVE,MOVE,MOVE]
global.FIREANT_COST = 510

global.BOMBERANT_TYPENAME = "bomberAnt"
global.BOMBERANT_PARTS = [TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE]
global.BOMBERANT_COST = 460

global.PHARAONANT_TYPENAME = "pharaonAnt"
global.PHARAONANT_PARTS = [CLAIM, MOVE]
global.PHARAONANT_COST = 650


global.TTL_ALERT = 5
