version: "2"
volumes:
  graphite_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./graphite_conf"
  statsd_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./statsd_conf"
  graphite_data:
  grafana_data:
services:
  node-shard2:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    links:
     - graphite-statsd
    environment:
      GRAPHITE_PORT_8125_UDP_ADDR: "graphite-statsd"
    env_file: docker-compose-shard2.env
  node-shard3:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    links:
     - graphite-statsd
    environment:
      GRAPHITE_PORT_8125_UDP_ADDR: "graphite-statsd"
    env_file: docker-compose-shard3.env
  graphite-statsd: 
    image: graphiteapp/graphite-statsd
    restart: always
    volumes:
     - graphite_conf:/opt/graphite/conf
     - graphite_data:/opt/graphite/storage/whisper
     - statsd_conf:/opt/statsd/config
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
     - grafana_data:/var/lib/grafana
    links:
     - graphite-statsd
    ports:
     - "1337:3000"