{
 "title": "Account info",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GCL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GCL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(stats.gauges.$shard.gcl.level)"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(maxSeries(stats.gauges.$shard.gcl.progress), #B)",
     "targetFull": "divideSeries(maxSeries(stats.gauges.$shard.gcl.progress), averageSeries(stats.gauges.$shard.gcl.progressTotal)\n)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "stat",
   "description": "based on last 1h",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(maxSeries(stats.gauges.$shard.gcl.progressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(maxSeries(stats.gauges.$shard.gcl.progressTotal), maxSeries(stats.gauges.$shard.gcl.progress)), scaleToSeconds(movingAverage(nonNegativeDerivative(maxSeries(stats.gauges.$shard.gcl.progress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress)), averageSeries(derivative(stats.gauges.$shard.tick.current))), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress)), averageSeries(derivative(stats.gauges.$shard.tick.current))), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  { "title": "GPL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GPL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(stats.gauges.$shard.gpl.level)"
    }
   ]
  },
  {
   "title": "GPL Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(maxSeries(stats.gauges.$shard.gpl.progress), #B)",
     "targetFull": "divideSeries(maxSeries(stats.gauges.$shard.gpl.progress), maxSeries(stats.gauges.$shard.gpl.progressTotal))"
    }
   ]
  },
  {
   "title": "Time to Next GPL",
   "type": "stat",
   "description": "based on last 1h",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(maxSeries(stats.gauges.$shard.gpl.progressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(maxSeries(stats.gauges.$shard.gpl.progressTotal), maxSeries(stats.gauges.gpl.$shard.progress)), scaleToSeconds(movingAverage(nonNegativeDerivative(maxSeries(stats.gauges.$shard.gpl.progress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GPL Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress)), averageSeries(derivative(stats.gauges.$shard.tick.current))), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(averageSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress)), averageSeries(derivative(stats.gauges.$shard.tick.current))), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Pixel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pixel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(stats.gauges.$shard.pixels)"
    }
   ]
  },
  {
   "title": "Time per Pixel",
   "type": "stat",
   "description": "based on last 1h",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1/$B", "type": "math" }
   ]
  },
  {
   "title": "Time per Decor",
   "type": "stat",
   "description": "based on last week",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "500/$B", "type": "math" }
   ]
  },
  {
   "title": "Decor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "floor($A / 500)", "type": "math" }
   ]
  },
  {
   "title": "Decor Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/500/200", "type": "math" }
   ]
  },
  {
   "title": "Time to Next Decor",
   "type": "stat",
   "description": "based on last 1h",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.$shard.pixels" },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(movingAverage(#B, '1hour')), 1)",
     "targetFull": "scaleToSeconds(nonNegativeDerivative(movingAverage(stats.gauges.$shard.pixels, '1hour')), 1)"
    },
    { "expression": "($B % 500) / $C", "type": "math" }
   ]
  },
  {
   "title": "Basic Perfomance $shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.used), 'Used')"
    },
    {
     "target": "alias(averageSeries(stats.gauges.$shard.cpu.bucket), 'Bucket')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.limit), 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$shard.cpu.bucket, 2)"
    }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(derivative(stats.gauges.$shard.tick.current), '(\\.tick\\.current\\))$', ' '), '(derivative\\(stats\\.gauges\\.)', 'Ticks Per Update ')"
    }
   ]
  }
 ]
}