{
 "title": "Energy economy",
 "tags": [
  "screeps",
  "economy"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "hiveName",
    "query": {}
   },
   { "name": "resource", "query": "energy" }
  ]
 },
 "panels": [
  { "title": "Colony info $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "shard" },
  {
   "title": "$resource per tick ",
   "type": "timeseries",
   "description": "with import/export",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(movingSum(transformNull(sumSeries(group(#E, #F)), 0), '5min'), #B), '5m average')",
     "targetFull": "alias(divideSeries(movingSum(transformNull(sumSeries(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*)), 0), '5min'), movingSum(derivative(stats.gauges.$shard.tick.current), '5min')), '5m average')"
    },
    {
     "target": "alias(divideSeries(movingSum(transformNull(sumSeries(group(#E, #F)), 0), '1hour'), #D), '1h average')",
     "targetFull": "alias(divideSeries(movingSum(transformNull(sumSeries(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*)), 0), '1hour'), movingSum(derivative(stats.gauges.$shard.tick.current), '1hour')), '1h average')"
    }
   ]
  },
  {
   "title": "Income/Expenditure",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(absolute(sumSeries(averageBelow(group(#A, #D), -0.000001))), 'Expenditure')",
     "targetFull": "alias(absolute(sumSeries(averageBelow(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), -0.000001))), 'Expenditure')"
    },
    {
     "target": "alias(sumSeries(averageAbove(group(#A, #D), 0.000001)), 'Income')",
     "targetFull": "alias(sumSeries(averageAbove(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 0.000001)), 'Income')"
    }
   ]
  },
  {
   "title": "$resource over period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(averageAbove(groupByNode(group(#C, #D), 7, 'sum'), 0.000001)), 'Income')",
     "targetFull": "alias(sumSeries(averageAbove(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 7, 'sum'), 0.000001)), 'Income')"
    },
    {
     "target": "alias(sumSeries(averageBelow(groupByNode(group(#C, #D), 7, 'sum'), -0.000001)), 'Expenditure')",
     "targetFull": "alias(sumSeries(averageBelow(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 7, 'sum'), -0.000001)), 'Expenditure')"
    }
   ]
  },
  {
   "title": "$resource income ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(absolute(averageAbove(group(#A, #C), 0.000001)), 7, 'sum')",
     "targetFull": "groupByNode(absolute(averageAbove(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*), 0.000001)), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$resource expenditure ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(absolute(averageBelow(group(#A, #C), -0.000001))), 7, 'sum')",
     "targetFull": "groupByNode(removeEmptySeries(absolute(averageBelow(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*), -0.000001))), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$resource per tick 10m average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(transformNull(sortByTotal(removeEmptySeries(divideSeries(movingAverage(groupByNode(group(#B, #D), 7, 'sum'), '10min'), #A))), 0), 0)",
     "targetFull": "aliasByNode(transformNull(sortByTotal(removeEmptySeries(divideSeries(movingAverage(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.*.resourceEvents.$resource.*), 7, 'sum'), '10min'), movingAverage(derivative(stats.gauges.$shard.tick.current), '10min')))), 0), 0)"
    }
   ]
  },
  {
   "title": "$resource income ",
   "type": "piechart",
   "description": "not ideal as some overlap is still there",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#C, 'Queen_bee|Carpenter_bee')), 'managers')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Queen_bee|Carpenter_bee')), 'managers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Honey_bee')), 'upgrader')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Honey_bee')), 'upgrader')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Mason_bee')), 'builder')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Mason_bee')), 'builder')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'depositmining')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'depositmining')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Japanese_beetle')), 'mineralmining')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Japanese_beetle')), 'mineralmining')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Scarabaeus_sacer')), 'energymining')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Scarabaeus_sacer')), 'energymining')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Bumblebee')), 'haulers')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Bumblebee')), 'haulers')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Walking_stick')), 'defense')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Walking_stick')), 'defense')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), 'annexupkeep')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Orchid_Mantis|Firefly')), 'annexupkeep')"
    },
    {
     "target": "alias(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth')), 'powermining')",
     "targetFull": "alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Hercules_beetle|Atlas_moth')), 'powermining')"
    },
    {
     "target": "alias(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attackers')",
     "targetFull": "alias(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attackers')"
    },
    {
     "target": "alias(diffSeries(sumSeries(#C), #A, #B, #D, #E, #F, #G, #H, #I, #J, #K, #L), 'other')",
     "targetFull": "alias(diffSeries(sumSeries(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.'))), alias(sumSeries(grep(absolute(grep(stats.gauges.$shard.hives.*.resourceEvents.$resource.*.*, '\\.spawn\\.')), 'Queen_bee|Carpenter_bee')), 'managers'), alias(sumSeries(grep(#C, 'Honey_bee')), 'upgrader'), alias(sumSeries(grep(#C, 'Mason_bee')), 'builder'), alias(sumSeries(grep(#C, 'Garden_bumblebee|Ground_beetle|Dragonfly')), 'depositmining'), alias(sumSeries(grep(#C, 'Japanese_beetle')), 'mineralmining'), alias(sumSeries(grep(#C, 'Scarabaeus_sacer')), 'energymining'), alias(sumSeries(grep(#C, 'Bumblebee')), 'haulers'), alias(sumSeries(grep(#C, 'Walking_stick')), 'defense'), alias(sumSeries(grep(#C, 'Orchid_Mantis|Firefly')), 'annexupkeep'), alias(sumSeries(grep(#C, 'Hercules_beetle|Atlas_moth')), 'powermining'), alias(grep(#C, 'Housefly|Luna_moth|European_hornet|Red_paper_wasp|Assasin_bug|Leaf_insect'), 'attackers')), 'other')"
    }
   ]
  },
  {
   "title": "$hiveName Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.spawners), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.storage), 'Storage')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.terminal), 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.storage), 'Storage'), alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.spawners), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.terminal), 'Terminal')), 'Total')"
    }
   ]
  },
  { "title": "$hiveName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "hiveName" },
  {
   "title": "$resource per Tick $hiveName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(transformNull(divideSeries(movingSum(sumSeries(group(#A, #D)), '10min'), #B), 0), '10m average')",
     "targetFull": "alias(transformNull(divideSeries(movingSum(sumSeries(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*)), '10min'), movingSum(derivative(stats.gauges.$shard.tick.current), '10min')), 0), '10m average')"
    }
   ]
  },
  {
   "title": "$hiveName Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.spawners), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.storage), 'Storage')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.terminal), 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.storage), 'Storage'), alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.spawners), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.terminal), 'Terminal')), 'Total')"
    }
   ]
  },
  {
   "title": "$resource income $hiveName",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(absolute(averageAbove(group(#A, #C), 0.000001))), 7, 'sum')",
     "targetFull": "groupByNode(removeEmptySeries(absolute(averageAbove(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*), 0.000001))), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$resource expenditure $hiveName",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(absolute(averageBelow(group(#A, #C), -0.000001))), 7, 'sum')",
     "targetFull": "groupByNode(removeEmptySeries(absolute(averageBelow(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.$resource.*.*), -0.000001))), 7, 'sum')"
    }
   ]
  }
 ]
}