{
 "title": "Dashboard",
 "tags": [ "screeps" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "hive", "query": "stats.gauges.hives.*" },
   {
    "name": "resource",
    "query": "stats.gauges.hives.$hive.resourceBalance.*"
   },
   { "name": "phase", "query": "stats.gauges.cpuUsage.*" },
   { "name": "processes", "query": "25" }
  ]
 },
 "panels": [
  { "title": "CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.cpu.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(stats.gauges.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.cpu.bucket" }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(stats.gauges.time), 'Ticks Per Update')"
    }
   ]
  },
  { "title": "CPU insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Apiary",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(highestAverage(movingAverage(stats.gauges.cpuUsage.$phase.*.cpu, '5min'), $processes), 3, 4))"
    },
    { "target": "*" }
   ]
  },
  {
   "title": "CPU Apiary norm",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(highestAverage(movingAverage(stats.gauges.cpuUsage.$phase.*.norm, '5min'), $processes), 3, 4))"
    }
   ]
  },
  {
   "title": "Intershard economy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Credits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(stats.gauges.credits, 'credits')"
      }
     ]
    },
    {
     "title": "Pixels",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "alias(stats.gauges.pixels, 'pixels')"
      }
     ]
    },
    {
     "title": "Decoration progress",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 17, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($A % 500) / 500", "type": "math" }
     ]
    },
    {
     "title": "Time to Decoration",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "( 500 - ($B % 500)) /  $C", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "$hive RLC and Nukes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "room",
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "stats.gauges.hives.$hive.controllerLevel"
      }
     ]
    },
    {
     "title": "RCL progress",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "divideSeries(stats.gauges.hives.$hive.controllerProgress, #B)",
       "targetFull": "divideSeries(stats.gauges.hives.$hive.controllerProgress, stats.gauges.hives.$hive.controllerProgressTotal)"
      }
     ]
    },
    {
     "title": "Time to Next RCL",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "divideSeries(diffSeries(stats.gauges.hives.$hive.controllerProgressTotal, #B), #C)",
       "targetFull": "divideSeries(diffSeries(stats.gauges.hives.$hive.controllerProgressTotal, stats.gauges.hives.$hive.controllerProgress), scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.hives.$hive.controllerProgress), '1hour'), 1))"
      }
     ]
    },
    {
     "title": "RCL Upgrade",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hive.controllerProgress), #C), 'RCL per tick')",
       "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hive.controllerProgress), derivative(stats.gauges.time)), 'RCL per tick')"
      },
      {
       "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hive.controllerProgress), #C), '1hour'), '1hr Moving Average')",
       "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hive.controllerProgress), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
      }
     ]
    },
    {
     "title": "Nukes",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "refCount": 1,
       "target": "aliasByNode(divideSeries(removeEmptySeries(#A), #C), 6)",
       "targetFull": "aliasByNode(divideSeries(removeEmptySeries(stats.gauges.hives.$hive.nukes.*.*), absolute(averageSeries(scaleToSeconds(movingAverage(derivative(stats.gauges.hives.$hive.nukes.*.*), '1hour'), 1)))), 6)"
      }
     ]
    }
   ]
  },
  { "title": "$hive economy overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "resource state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode(movingAverage(stats.gauges.hives.$hive.resState.*, '10min'), 5)"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(stats.gauges.hives.$hive.energyAvailable, 'Spawns and Extensions')"
    },
    {
     "refCount": 1,
     "target": "alias(stats.gauges.hives.$hive.storageEnergy, 'Storage')"
    },
    {
     "refCount": 1,
     "target": "alias(stats.gauges.hives.$hive.terminalEnergy, 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(stats.gauges.hives.$hive.storageEnergy, 'Storage'), alias(stats.gauges.hives.$hive.energyAvailable, 'Spawns and Extensions'), alias(stats.gauges.hives.$hive.terminalEnergy, 'Terminal')), 'Total')"
    }
   ]
  },
  {
   "title": "$hive energy economy overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": -1,
       "target": "aliasByNode(removeBelowValue(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), 0.00001), 5)"
      },
      {
       "target": "alias(sumSeries(#A), 'Total')",
       "targetFull": "alias(sumSeries(aliasByNode(removeBelowValue(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), 0.00001), 5)), 'Total')"
      }
     ]
    },
    {
     "title": "Losses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": -1,
       "target": "aliasByNode(removeAboveValue(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), -0.00001), 5)"
      },
      {
       "target": "alias(sumSeries(#A), 'Total')",
       "targetFull": "alias(sumSeries(aliasByNode(removeAboveValue(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), -0.00001), 5)), 'Total')"
      }
     ]
    },
    {
     "title": "State",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "refCount": 1,
       "target": "alias(sumSeries(removeAboveValue(#A, -0.00001)), 'expenditure')",
       "targetFull": "alias(sumSeries(removeAboveValue(aliasByNode(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), 5), -0.00001)), 'expenditure')"
      },
      {
       "refCount": 1,
       "target": "alias(sumSeries(#A), 'Total')",
       "targetFull": "alias(sumSeries(aliasByNode(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), 5)), 'Total')"
      },
      {
       "refCount": 1,
       "target": "alias(sumSeries(removeBelowValue(#A, 0.00001)), 'income')",
       "targetFull": "alias(sumSeries(removeBelowValue(aliasByNode(movingAverage(stats.gauges.hives.$hive.energyReport.*.profit, '10min'), 5), 0.00001)), 'income')"
      }
     ]
    }
   ]
  },
  {
   "title": "$hive $resource economy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$resource per tick",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(divideSeries(aliasByNode(movingAverage(stats.gauges.hives.$hive.resourceBalance.$resource.*.amount, '30min'), 6), #C), 0)",
       "targetFull": "aliasByNode(divideSeries(aliasByNode(movingAverage(stats.gauges.hives.$hive.resourceBalance.$resource.*.amount, '30min'), 6), alias(diffSeries(movingAverage(stats.gauges.time, '30min'), movingAverage(averageSeries(stats.gauges.hives.$hive.resourceBalance.$resource.*.time), '30min')), 'time')), 0)"
      }
     ]
    },
    {
     "title": "$resource income",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "refCount": 1,
       "target": "removeEmptySeries(aliasByNode(removeBelowValue(#D, 0.00001), 0))",
       "targetFull": "removeEmptySeries(aliasByNode(removeBelowValue(aliasByNode(divideSeries(aliasByNode(movingAverage(stats.gauges.hives.$hive.resourceBalance.$resource.*.amount, '30min'), 6), alias(diffSeries(movingAverage(stats.gauges.time, '30min'), movingAverage(averageSeries(stats.gauges.hives.$hive.resourceBalance.$resource.*.time), '30min')), 'time')), 0), 0.00001), 0))"
      }
     ]
    },
    {
     "title": "$resource expenditure",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "refCount": 1,
       "target": "removeEmptySeries(aliasByNode(absolute(removeAboveValue(#D, -0.00001)), 0))",
       "targetFull": "removeEmptySeries(aliasByNode(absolute(removeAboveValue(aliasByNode(divideSeries(aliasByNode(movingAverage(stats.gauges.hives.$hive.resourceBalance.$resource.*.amount, '30min'), 6), alias(diffSeries(movingAverage(stats.gauges.time, '30min'), movingAverage(averageSeries(stats.gauges.hives.$hive.resourceBalance.$resource.*.time), '30min')), 'time')), 0), -0.00001)), 0))"
      }
     ]
    }
   ]
  },
  {
   "title": "GCL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "GCL",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "target": "stats.gauges.gcl.level" }
     ]
    },
    {
     "title": "GCL Progress",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "divideSeries(stats.gauges.gcl.progress, #B)",
       "targetFull": "divideSeries(stats.gauges.gcl.progress, stats.gauges.gcl.progressTotal)"
      }
     ]
    },
    {
     "title": "Time to Next GCL",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "divideSeries(diffSeries(stats.gauges.gcl.progressTotal, #B), #C)",
       "targetFull": "divideSeries(diffSeries(stats.gauges.gcl.progressTotal, stats.gauges.gcl.progress), scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.gcl.progress), '1hour'), 1))"
      }
     ]
    },
    {
     "title": "GCL Upgrade",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), #B), 'GCL per tick')",
       "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), derivative(stats.gauges.time)), 'GCL per tick')"
      },
      {
       "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), #B), '1hour'), '1hr Moving Average')",
       "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
      }
     ]
    }
   ]
  },
  {
   "title": "GPL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPL",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "target": "stats.gauges.gpl.level" }
     ]
    },
    {
     "title": "GPL Progress",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "divideSeries(stats.gauges.gpl.progress, #B)",
       "targetFull": "divideSeries(stats.gauges.gpl.progress, stats.gauges.gpl.progressTotal)"
      }
     ]
    },
    {
     "title": "Time to Next GPL",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "divideSeries(diffSeries(stats.gauges.gpl.progressTotal, #B), #C)",
       "targetFull": "divideSeries(diffSeries(stats.gauges.gpl.progressTotal, stats.gauges.gpl.progress), scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.gpl.progress), '1hour'), 1))"
      }
     ]
    },
    {
     "title": "GPL Upgrade",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.gpl.progress), #B), 'GCL per tick')",
       "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.gpl.progress), derivative(stats.gauges.time)), 'GCL per tick')"
      },
      {
       "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.gpl.progress), #B), '1hour'), '1hr Moving Average')",
       "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.gpl.progress), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
      }
     ]
    }
   ]
  }
 ]
}