version: "2"
volumes:
  graphite_data:
  grafana_data:
services:
  node:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    links:
     - statsd
    environment:
      GRAPHITE_PORT_8125_UDP_ADDR: "statsd"
    env_file: docker-compose.env
    logging:
      driver: none
  statsd:
    image: ennexa/statsd
    links:
     - graphite
  graphite:
    image: ennexa/graphite
    restart: always
    volumes:
     - /opt/graphite/conf
     - graphite_data:/opt/graphite/storage/whisper
    logging:
      driver: none
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
     - grafana_data:/var/lib/grafana
    links:
     - graphite
    ports:
     - "1337:3000"
    logging:
      driver: none
