export const PUNS_UPTIME = 12;

export const HIVE_MAJESTY_PUNS = (Array(100).fill("🐝") as string[]).concat([
  "BzzZzZ",
  "🐝🤖",
  "🍯👑",
]);

export const HIVE_MAJESTY_SLOGANS = [
  "In the Realm of Battle, Hive Majesty's Stinger Reigns Supreme.",
  "Where Bees of Battle Buzz, Hive Majesty Holds Court.",
  "Bee-hold the Majestic Power of Hive Majesty – The Crown Jewel of the Arena!",
  "With Hive Majesty, Victory is Sweeter than the Finest Honey.",
  "In the Hive of Champions, Hive Majesty Wears the Royal Crown.",
  "Let the Royal Stinger of Hive Majesty Pierce the Heart of Victory!",
  "Rule the Battlefield with Royal Grace – Choose Hive Majesty!",
  "From Hive to Victory, Hive Majesty's Dominion Knows No Bounds.",
  "Majestic Power, Honeyed Victory – Hive Majesty Commands All.",
  "As Bees to a Hive, Warriors to Hive Majesty – Loyalty, Victory, and Glory!",
  "With Hive Majesty, Every Battle is a Royal Triumph.",
  "In the Kingdom of Battle Bots, Hive Majesty Reigns Supreme.",
  "Sting with Majesty, Rule with Elegance.",
  "Bee-lieve in Hive Majesty for Unstoppable Dominance!",
  "In Every Arena, Hive Majesty is the Regent of Victory.",
  "With Hive Majesty, Victory is as Certain as the Sunrise.",
  "Hive Majesty's Stinger Strikes Swift and Sure, Victory is Assured.",
  "Majestic Sovereignty in Every Arena.",
  "Embrace the Majesty of Supreme Victory with Hive Majesty.",
  "The Regal Essence of Hive Majesty Elevates Victory to Royalty.",
  "Defying Limits, Embracing Domination – Hive Majesty's Royal Decree.",
  "In the Hive of Champions, Hive Majesty Reigns Unchallenged.",
  "Majestic Excellence, Unrivaled Dominance.",
  "Victory, Royalty, and the Unyielding Power of Hive Majesty.",
  "Bee-lieve in Victory, Bow to Majesty – Choose Hive Majesty!",
  "A Majestic Legacy of Unstoppable Victory.",
  "Hive Majesty Commands the Arena, Ruling with a Regal Sting.",
  "With Hive Majesty, Conquer the Battle, Claim the Throne.",
  "Hive Majesty: The Royal Path to Conquest.",
  "For Majestic Triumphs, Hive Majesty Leads the Way.",
  "Embrace the Royal Sting, Conquer with Hive Majesty!",
  "The Sweet Taste of Victory: Hive Majesty's Honeyed Crown.",
  "The Sovereign Power of Hive Majesty.",
  "Majestic Mastery Unleashed in Every Battle with Hive Majesty.",
  "Majestic Sovereignty in Every Arena.",
  "With Hive Majesty, Every Victory is Honey-Dipped.",
  "In Battle, Majesty Prevails – Hive Majesty's Royal Decree.",
  "The Hive of Champions, Where Hive Majesty Reigns Supreme.",
  "Rule with Majesty, Sting with Power – Choose Hive Majesty!",
  "In the Kingdom of Battle Bots, Hive Majesty Rules with a Royal Sting.",
  "The Regal Majesty of Hive Majesty: Where Victory Becomes Royalty.",
  "Majesty's Stinger Strikes Swift and Sure, Victory is the Crown Jewel.",
  "Unleash the Royal Sting, Witness the Conquest with Hive Majesty!",
  "Victory Fit for Royalty, Crafted by Hive Majesty's Hand.",
  "From Hive to Glory, Hive Majesty's Dominion Knows No Bounds.",
  "With Hive Majesty, Triumph is Sweet as the Purest Honey.",
  "In Every Arena, Hive Majesty is the Regent of Victory.",
  "Majestic Power, Honeyed Victory – Hive Majesty Commands All.",
  "Bee-hold the Reign of Hive Majesty, Where Victory is the Nectar of Champions.",
  "As Bees to a Hive, Warriors to Hive Majesty – Loyalty, Victory, and Glory!",
  "With Hive Majesty, Every Battle is a Royal Triumph.",
  "In the Kingdom of Battle Bots, Hive Majesty Reigns Supreme.",
  "Sting with Majesty, Rule with Elegance.",
  "Bee-lieve in Hive Majesty for Unstoppable Dominance!",
  "In Every Arena, Hive Majesty is the Regent of Victory.",
  "With Hive Majesty, Victory is as Certain as the Sunrise.",
  "Hive Majesty's Stinger Strikes Swift and Sure, Victory is Assured.",
  "Majestic Sovereignty in Every Arena.",
  "Embrace the Majesty of Supreme Victory with Hive Majesty.",
  "The Regal Essence of Hive Majesty Elevates Victory to Royalty.",
  "Defying Limits, Embracing Domination – Hive Majesty's Royal Decree.",
  "In the Hive of Champions, Hive Majesty Reigns Unchallenged.",
  "Majestic Excellence, Unrivaled Dominance.",
  "Victory, Royalty, and the Unyielding Power of Hive Majesty.",
  "Bee-lieve in Victory, Bow to Majesty – Choose Hive Majesty!",
  "A Majestic Legacy of Unstoppable Victory.",
  "Hive Majesty Commands the Arena, Ruling with a Regal Sting.",
  "With Hive Majesty, Conquer the Battle, Claim the Throne.",
  "Hive Majesty: The Royal Path to Conquest.",
  "For Majestic Triumphs, Hive Majesty Leads the Way.",
  "Embrace the Royal Sting, Conquer with Hive Majesty!",
  "The Sweet Taste of Victory: Hive Majesty's Honeyed Crown.",
  "The Sovereign Power of Hive Majesty.",
  "Majestic Mastery Unleashed in Every Battle with Hive Majesty.",
  "Majestic Sovereignty in Every Arena.",
  "With Hive Majesty, Every Victory is Honey-Dipped.",
  "In Battle, Majesty Prevails – Hive Majesty's Royal Decree.",
  "The Hive of Champions, Where Hive Majesty Reigns Supreme.",
  "Rule with Majesty, Sting with Power – Choose Hive Majesty!",
  "In the Kingdom of Battle Bots, Hive Majesty Rules with a Royal Sting.",
  "The Regal Majesty of Hive Majesty: Where Victory Becomes Royalty.",
];
