steamKey: "A90B290A72B8580A80078FAA454E8BC8"
mods: # Recommended mods
- screepsmod-auth
- screepsmod-admin-utils
- screepsmod-mongo  # You must install and start `mongodb` and `redis` before this mod will work
- screepsmod-map-tool
- screepsmod-history
- screepsmod-market
bots:
  simplebot: "screepsbot-zeswarm"
#  overmind: "./bots/overmind/dist"
serverConfig: # This section requires screepsmod-admin-utils to work
  welcomeText:  |
    <h1 style="text-align: center;">My Cool Server</h1>
  constants: # Used to override screeps constants
    TEST_CONSTANT: 123
  tickRate: 1000  # In milliseconds. This is a lower bound. Users reported problems when set too low.
pinnedPackages:
  ssri: 9.0.1
  cacache: 16.1.3
  minipass: 4.2.8
  tar: 5.0.11
  minipass-fetch: 2.1.2
  make-fetch-happen: 10.2.1
  node-gyp: 9.4.0