{
 "title": "Account status",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "hiveName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Perfomance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.used), 'Used')"
    },
    {
     "target": "alias(averageSeries(stats.gauges.$shard.cpu.bucket), 'Bucket')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.limit), 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$shard.cpu.bucket, 2)"
    }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasSub(aliasSub(derivative(stats.gauges.$shard.tick.current), '(\\.tick\\.current\\))$', ' '), '(derivative\\(stats\\.gauges\\.)', 'Ticks Per Update ')"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GCL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.$shard.gcl.level" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(stats.gauges.$shard.gcl.progress, #B)",
     "targetFull": "divideSeries(stats.gauges.$shard.gcl.progress, stats.gauges.$shard.gcl.progressTotal)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.$shard.gcl.progressTotal, #B), #C)",
     "targetFull": "divideSeries(diffSeries(stats.gauges.$shard.gcl.progressTotal, stats.gauges.$shard.gcl.progress), scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.$shard.gcl.progress), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress), derivative(stats.gauges.$shard.tick.current)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gcl.progress), derivative(stats.gauges.$shard.tick.current)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  { "title": "GPL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GPL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.$shard.gpl.level" }
   ]
  },
  {
   "title": "GPL Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(stats.gauges.$shard.gpl.progress, #B)",
     "targetFull": "divideSeries(stats.gauges.$shard.gpl.progress, stats.gauges.$shard.gpl.progressTotal)"
    }
   ]
  },
  {
   "title": "Time to Next GPL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeries(divideSeries(stats.gauges.$shard.gpl.progressTotal, #C), #B)",
     "targetFull": "diffSeries(divideSeries(stats.gauges.$shard.gpl.progressTotal, scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.$shard.gpl.progress), '1hour'), 1)), stats.gauges.gpl.$shard.progress)"
    }
   ]
  },
  {
   "title": "GPL Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress), derivative(stats.gauges.$shard.tick.current)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.$shard.gpl.progress), derivative(stats.gauges.$shard.tick.current)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "$hiveName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "hiveName",
   "targets": [
    {}
   ]
  },
  {
   "title": "RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.$shard.hives.$hiveName.controller.level"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(stats.gauges.$shard.hives.$hiveName.controller.progress, #B)",
     "targetFull": "divideSeries(stats.gauges.$shard.hives.$hiveName.controller.progress, transformNull(stats.gauges.$shard.hives.$hiveName.controller.progressTotal, 1))"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.$shard.hives.$hiveName.controller.progressTotal, #B), #C)",
     "targetFull": "divideSeries(diffSeries(stats.gauges.$shard.hives.$hiveName.controller.progressTotal, stats.gauges.$shard.hives.$hiveName.controller.progress), scaleToSeconds(movingAverage(nonNegativeDerivative(stats.gauges.$shard.hives.$hiveName.controller.progress), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.hives.$hiveName.controller.progress), #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(stats.gauges.$shard.hives.$hiveName.controller.progress), derivative(stats.gauges.$shard.tick.current)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hiveName.controller.progress), #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.hives.$hiveName.controller.progress), derivative(stats.gauges.$shard.tick.current)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$shard.hives.$hiveName.energy.spawners, 'Spawns and Extensions')"
    },
    {
     "target": "alias(stats.gauges.$shard.hives.$hiveName.energy.storage, 'Storage')"
    },
    {
     "target": "alias(stats.gauges.hives.$hiveName.energy.terminal, 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(stats.gauges.$shard.hives.$hiveName.energy.storage, 'Storage'), alias(stats.gauges.$shard.hives.$hiveName.energy.spawners, 'Spawns and Extensions'), alias(stats.gauges.hives.$hiveName.energy.terminal, 'Terminal')), 'Total')"
    }
   ]
  }
 ]
}