{
 "title": "CPU performance",
 "tags": [
  "screeps",
  "perfomance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "mode",
    "query": {}
   },
   {
    "name": "phase",
    "query": {}
   },
   { "name": "scaling", "query": "0.001" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU by Phase",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(scale(removeEmptySeries(stats.gauges.$shard.cpuUsage.*.*.$mode), $scaling), 4, 'sum')"
    }
   ]
  },
  {
   "title": "Mean CPU by Phase",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(stats.gauges.$shard.cpuUsage.*.*.$mode), 4, 'sum')"
    }
   ]
  },
  {
   "title": "Total CPU by Category",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#A, 'deposit')), 'deposit mining')",
     "targetFull": "alias(sumSeries(grep(groupByNode(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'structures_room_')), 'hive update structures')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'network')), 'network')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'network')), 'network')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'warcrimes')), 'warcrimes')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'log|visuals')), 'convinience')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'log|visuals')), 'convinience')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'beesMove')), 'beesMove')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'beesMove')), 'beesMove')"
    },
    {
     "target": "alias(absolute(sumSeries(scale(#B, -1), #C, #D, #E, #F, #G, #H, #I, #J, #K, #M)), 'other')",
     "targetFull": "alias(absolute(sumSeries(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), -1), alias(sumSeries(grep(groupByNode(grep(#B, '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining'), alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense'), alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures'), alias(sumSeries(grep(#B, 'network')), 'network'), alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes'), alias(sumSeries(grep(#B, 'log|visuals')), 'convinience'), alias(sumSeries(grep(#B, 'beesMove')), 'beesMove'))), 'other')"
    }
   ]
  },
  {
   "title": "Mean CPU by Category",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#A, 'deposit')), 'deposit mining')",
     "targetFull": "alias(sumSeries(grep(groupByNode(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'structures_room_')), 'hive update structures')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'network')), 'network')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'network')), 'network')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'warcrimes')), 'warcrimes')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'log|visuals')), 'convinience')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'log|visuals')), 'convinience')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'beesMove')), 'beesMove')",
     "targetFull": "alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'beesMove')), 'beesMove')"
    },
    {
     "target": "alias(absolute(sumSeries(scale(#B, -1), #C, #D, #E, #F, #G, #H, #I, #J, #K, #M)), 'other')",
     "targetFull": "alias(absolute(sumSeries(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), -1), alias(sumSeries(grep(groupByNode(grep(#B, '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining'), alias(sumSeries(grep(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense'), alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures'), alias(sumSeries(grep(#B, 'network')), 'network'), alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes'), alias(sumSeries(grep(#B, 'log|visuals')), 'convinience'), alias(sumSeries(grep(#B, 'beesMove')), 'beesMove'))), 'other')"
    }
   ]
  },
  {
   "title": "CPU general",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.used), 'Used')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.bucket), 'Bucket')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.cpu.limit), 'Limit')"
    },
    {
     "target": "alias(scale(sumSeries(stats.gauges.$shard.cpuUsage.$phase.*.cpu), $scaling), 'Accounted')"
    }
   ]
  },
  {
   "title": "CPU by Category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(sumSeries(grep(#A, 'deposit')), 'deposit mining')",
     "targetFull": "alias(sumSeries(grep(groupByNode(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'structures_room_')), 'hive update structures')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'network')), 'network')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'network')), 'network')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'warcrimes')), 'warcrimes')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'log|visuals')), 'convinience')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'log|visuals')), 'convinience')"
    },
    {
     "target": "alias(sumSeries(grep(#B, 'beesMove')), 'beesMove')",
     "targetFull": "alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'beesMove')), 'beesMove')"
    },
    {
     "target": "alias(absolute(sumSeries(scale(#B, -1), #C, #D, #E, #F, #G, #H, #I, #J, #K, #M)), 'other')",
     "targetFull": "alias(absolute(sumSeries(scale(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), -1), alias(sumSeries(grep(groupByNode(grep(#B, '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining'), alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense'), alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures'), alias(sumSeries(grep(#B, 'network')), 'network'), alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes'), alias(sumSeries(grep(#B, 'log|visuals')), 'convinience'), alias(sumSeries(grep(#B, 'beesMove')), 'beesMove'))), 'other')"
    },
    {
     "target": "alias(sumSeries(#C, #D, #E, #F, #G, #H, #I, #J, #K, #L, #M), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(grep(groupByNode(grep(#B, '^(run|update)\\.master.*'), 1, 'sum'), 'deposit')), 'deposit mining'), alias(sumSeries(grep(scale(removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5)), $scaling), 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense'), alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures'), alias(sumSeries(grep(#B, 'network')), 'network'), alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes'), alias(sumSeries(grep(#B, 'log|visuals')), 'convinience'), alias(absolute(sumSeries(scale(#B, -1), alias(sumSeries(grep(#A, 'deposit')), 'deposit mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(lab|factory|powerHive)')), 'hive production'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(spawn|dev|fastRef|storage|upgrade)')), 'hive operation'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(res|excav)|master_swarm_annex')), 'hive mining'), alias(sumSeries(grep(#B, 'cell_[A-Z1-9]+_(defHive|observe)')), 'hive defense'), alias(sumSeries(grep(#B, 'structures_room_')), 'hive update structures'), alias(sumSeries(grep(#B, 'network')), 'network'), alias(sumSeries(grep(#B, 'warcrimes')), 'warcrimes'), alias(sumSeries(grep(#B, 'log|visuals')), 'convinience'), alias(sumSeries(grep(#B, 'beesMove')), 'beesMove'))), 'other'), alias(sumSeries(grep(#B, 'beesMove')), 'beesMove')), 'Total')"
    }
   ]
  },
  {
   "title": "CPU by Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5))"
    }
   ]
  },
  {
   "title": "Total CPU by Process",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5))"
    }
   ]
  },
  {
   "title": "Mean CPU by Process",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5))"
    }
   ]
  },
  {
   "title": "Total CPU by Top10 Process",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(highestAverage(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 10), 4, 5))"
    }
   ]
  },
  {
   "title": "Mean CPU by TOP10 Process",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByNode(stats.gauges.$shard.cpuUsage.$phase.*.$mode, 4, 5))"
    }
   ]
  }
 ]
}