{
 "title": "Credits economy",
 "tags": [
  "screeps",
  "economy"
 ],
 "time": { "from": "now-5h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scaling", "query": "0.001" },
   {
    "name": "shard",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Credits spend to buy",
   "type": "piechart",
   "description": "With fees",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(scale(stats.gauges.$shard.market.resourceEvents.*.buy.*, $scaling), 5, 'sum')"
    }
   ]
  },
  {
   "title": "Credits from selling",
   "type": "piechart",
   "description": "Accounted for fees",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(scale(group(#A, #B), $scaling), 5, 'sum')",
     "targetFull": "groupByNode(scale(group(grep(stats.gauges.$shard.market.resourceEvents.*.sell.*, '(long|short)$'), scale(grep(stats.gauges.$shard.market.resourceEvents.*.sell.*, '\\.fee'), -1)), $scaling), 5, 'sum')"
    }
   ]
  },
  {
   "title": "Credits balance",
   "type": "gauge",
   "description": "With fees",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "scale(grep(stats.gauges.$shard.market.resourceEvents.*.sell.*, '\\.fee[a-zA-Z]$'), -1)"
    },
    {
     "target": "alias(scale(sumSeries(sumSeries(scale(stats.gauges.$shard.market.resourceEvents.*.buy.*, -1)), #D), $scaling), 'Expenditure ')",
     "targetFull": "alias(scale(sumSeries(sumSeries(scale(stats.gauges.$shard.market.resourceEvents.*.buy.*, -1)), scale(grep(stats.gauges.$shard.market.resourceEvents.*.sell.*, '\\.fee[a-zA-Z]$'), -1)), $scaling), 'Expenditure ')"
    },
    {
     "target": "alias(scale(sumSeries(grep(stats.gauges.$shard.market.resourceEvents.*.sell.*, '(long|short)$')), $scaling), 'Income')"
    }
   ]
  },
  {
   "title": "Credits Available ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(averageSeries(scale(stats.gauges.$shard.market.credits, 0.001)), 'Credits')"
    }
   ]
  },
  {
   "title": "Last balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(scale(stats.gauges.$shard.market.credits, 0.001)), 'Credits')"
    }
   ]
  },
  {
   "title": "Mean balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(scale(stats.gauges.$shard.market.credits, 0.001)), 'Credits')"
    }
   ]
  },
  {
   "title": "Diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(scale(stats.gauges.$shard.market.credits, $scaling)), 'Credits')"
    }
   ]
  },
  {
   "title": "Range balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(scale(stats.gauges.$shard.market.credits, 0.001)), 'Credits')"
    }
   ]
  },
  {
   "title": "Last trades",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(sortByTotal(scale(maximumAbove(stats.gauges.$shard.market.resourceEvents.*.*.*, 0.00001), $scaling)), 2, 5, 6, 7), '^(shard)', '\\1')"
    }
   ]
  }
 ]
}