{
 "title": "Energy economy",
 "tags": [ "screeps" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": {}
   },
   {
    "name": "hiveName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Colony info $shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "shard" },
  {
   "title": "Energy per tick 30m average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "alias(movingAverage(divideSeries(sumSeries(movingAverage(removeBelowValue(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), 0.000001), 1)), #B), '30min'), 'Income')",
     "targetFull": "alias(movingAverage(divideSeries(sumSeries(movingAverage(removeBelowValue(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), 0.000001), 1)), derivative(stats.gauges.$shard.tick.current)), '30min'), 'Income')"
    },
    {
     "target": "alias(movingAverage(divideSeries(transformNull(sumSeries(movingAverage(removeAboveValue(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), -0.000001), 1)), 0), #B), '30min'), 'Expenditure')",
     "targetFull": "alias(movingAverage(divideSeries(transformNull(sumSeries(movingAverage(removeAboveValue(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), -0.000001), 1)), 0), derivative(stats.gauges.$shard.tick.current)), '30min'), 'Expenditure')"
    }
   ]
  },
  {
   "title": "Energy income 10m average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "aliasSub(movingAverage(divideSeries(movingAverage(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7, 'sum'), 2), #A), '10min'), '^.*movingAverage\\(([a-z]+)\\,.+$', '\\1')",
     "targetFull": "aliasSub(movingAverage(divideSeries(movingAverage(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7, 'sum'), 2), movingAverage(derivative(stats.gauges.$shard.tick.current), 10)), '10min'), '^.*movingAverage\\(([a-z]+)\\,.+$', '\\1')"
    }
   ]
  },
  {
   "title": "Energy over period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(averageAbove(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7, 'sum'), 0.000001)), 'Income')"
    },
    {
     "target": "alias(sumSeries(averageBelow(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7, 'sum'), -0.000001)), 'Expenditure')"
    }
   ]
  },
  {
   "title": "Income/Expenditure",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(absolute(sumSeries(averageBelow(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7, 'sum'), -0.000001))), 'Expenditure')"
    },
    {
     "target": "alias(sumSeries(averageAbove(groupByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7, 'sum'), 0.000001)), 'Income')"
    }
   ]
  },
  {
   "title": "Energy Balance",
   "type": "timeseries",
   "description": "No import/export. Not even local import/export",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "alias(movingAverage(divideSeries(movingAverage(sumSeries(exclude(exclude(aliasByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7), 'export'), 'import')), 2), #B), '10min'), '10m average')",
     "targetFull": "alias(movingAverage(divideSeries(movingAverage(sumSeries(exclude(exclude(aliasByNode(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 7), 'export'), 'import')), 2), movingAverage(derivative(stats.gauges.$shard.tick.current), 10)), '10min'), '10m average')"
    }
   ]
  },
  {
   "title": "Rooms Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.*.energy.spawners), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.*.energy.storage), 'Storage')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.*.energy.terminal), 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.$shard.hives.*.energy.storage), 'Storage'), alias(sumSeries(stats.gauges.$shard.hives.*.energy.spawners), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.$shard.hives.*.energy.terminal), 'Terminal')), 'Total')"
    }
   ]
  },
  {
   "title": "Energy income",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(averageAbove(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), 0.000001), 7, 'sum')"
    }
   ]
  },
  {
   "title": "Energy expenditure ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "aliasByNode(groupByNode(absolute(averageBelow(group(stats.gauges.$shard.hives.*.resourceEvents.energy.*.*, stats.gauges.$shard.hives.*.resourceEvents.energy.*), -0.000001)), 7, 'sum'), 0)"
    }
   ]
  },
  { "title": "$hiveName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "hiveName" },
  {
   "title": "$hiveName Energy Balance ",
   "type": "timeseries",
   "description": "No import/export. Not even local import/export",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "alias(movingAverage(divideSeries(movingAverage(sumSeries(exclude(exclude(aliasByNode(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), 7), 'export'), 'import')), 2), #B), '10min'), '10m average')",
     "targetFull": "alias(movingAverage(divideSeries(movingAverage(sumSeries(exclude(exclude(aliasByNode(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), 7), 'export'), 'import')), 2), movingAverage(derivative(stats.gauges.$shard.tick.current), 10)), '10min'), '10m average')"
    }
   ]
  },
  {
   "title": "$hiveName Stored Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.spawners), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.storage), 'Storage')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.terminal), 'Terminal')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), 'Total')",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.storage), 'Storage'), alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.spawners), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.$shard.hives.$hiveName.energy.terminal), 'Terminal')), 'Total')"
    }
   ]
  },
  {
   "title": "$hiveName Energy income",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(averageAbove(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*), 0.000001), 7, 'sum')"
    }
   ]
  },
  {
   "title": "$hiveName Energy expenditure ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNode(absolute(averageBelow(group(stats.gauges.$shard.hives.$hiveName.resourceEvents.energy.*.*, stats.gauges.hives.$hiveName.resourceEvents.energy.*), -0.000001)), 7, 'sum')"
    }
   ]
  }
 ]
}